### ISSUE TITLE
Adjust PriceFeed.sol to updated Chainlink Smart Contracts 

### ISSUE THREAD

**Issue by udosson** [kumodao/borrowprot#100]
## Description
As a user of the lending protocol, I want the price feed logic to be based on the newest Chainlink smart contracts.

## Expected Outcome
Updated the all Chainlink related price feed logic
- [x] Update `./PriceFeed.sol`
- [x] Adjust price feed-related tests if needed

**Comment by arthurka-o** [comment]
No changes needed
