### ISSUE TITLE
Upgrade safemath.sol

### ISSUE THREAD

**Issue by udosson** [kumodao/borrowprot#18]
Upgrade https://github.com/kumodao/borrowprot/blob/upgrade-solidity-version/packages/contracts/contracts/Dependencies/SafeMath.sol according to openzeppelin at https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/utils/math/SafeMath.sol

**Comment by adi44** [comment]
I would like to contribute

**Comment by udosson** [comment]
@adi44 - I'm sorry for the late reply. Do you still want to contribute to the project?

**Comment by wollooo** [comment]
yes done [@24](https://github.com/kumodao/borrowprot/pull/24)
