### ISSUE TITLE
Test HardHat config for Polygon with sample test set up

### ISSUE THREAD

**Issue by udosson** [kumodao/borrowprot#32]
## Description
As a developer, I want to know how to configure hardhat to run Polygon-alike. To don't mess up too many things at once, I'd prefer to have a simple & working example I can use as a starting point.

## Expected Outcome
- [x] Create a local dummy test environment with hardhat
- [x] Run Polygon-alike hardhat locally
- [x] Run tests with hardhat that proves the working configuration

**Comment by arthurka-o** [comment]
I think we can move to "Done"; there's nothing to review/merge.

**Comment by udosson** [comment]
Alright. Thanks, @arthurka-o
