### ISSUE TITLE
Deploy dummy project to Mumbai network (Polygon testnet)

### ISSUE THREAD

**Issue by udosson** [kumodao/borrowprot#33]
## Description
As a developer, I want to regularly test the local development at the Mumbai network. To do so I need scripts that allow automated deployment. To write these scripts I want to have a working example with a dummy project as a good practice.

## Expected Outcome
- [ ] Create scripts that deploy a dummy project to Mumbai Testnet
- [ ] Configure Hardhat to deploy smart contracts to Mumbai Testnet
- [ ] Document the process with everything that's needed

**Comment by arthurka-o** [comment]
I think we don't need it. Default hardhat's deploy script works fine.

**Comment by udosson** [comment]
Alright. Thanks, @arthurka-o
