### ISSUE TITLE
Change Dependencies and Imports of smart contract from LUSD to KUSD

### ISSUE THREAD

**Issue by udosson** [kumodao/borrowprot#36]
## Description
As a smart contract developer, I want to use the KUSD ERC20 contract to finally mint KUSD in the system. To do so, I need to reference update the reference from LUSD to KUSD in all corresponding contracts

## Expected Outcomes
- [x] update all smart contracts in `./packages/contracts`
- [x] update all smart contracts in `./packages/dependencies`
- [x] update all smart contracts in `./packages/interfaces`
- [x] update all smart contracts in `./packages/LQTY`

**Comment by wollooo** [comment]
done at [#66](https://github.com/kumodao/borrowprot/pull/66)
