### ISSUE TITLE
Update all utils scripts of smart contracts to use KUSD token

### ISSUE THREAD

**Issue by udosson** [kumodao/borrowprot#38]
## Description
As a smart contract developer, I strive for 100% test coverage. Therefore, I need to integrate `KUSD` in all corresponding tests. I want to have utils scripts that make life easier. Thus, all KUSD-related scripts need to be updated.

## Expected Outcome
- [x] updated `./utils/deploymentGasAndBytecode.js` with `KUSD` contracts
- [x] updated `./utils/deploymentHelpers.js` with `KUSD`contracts
- [x] updated `./utils/hintExamples.js` with `KUSD` contracts
- [x] updated `./utils/mainnetDeploymentHelpers.js` with `KUSD` contracts
- [x] updated `./utils/proxyHelpers.js` with `KUSD` contracts
- [x] updated `./utils/testHelpers.js` with `KUSD` contracts
- [x] updated `./utils/truffleDeploymentHelpers .js` with `KUSD` contracts

**Comment by wollooo** [comment]
done at [#66](https://github.com/kumodao/borrowprot/pull/66)
