### ISSUE TITLE
Update all utils scripts of smart contracts to use KUMO token

### ISSUE THREAD

**Issue by udosson** [kumodao/borrowprot#41]
## Description
As a smart contract developer, I strive for 100% test coverage. Therefore, I need to integrate the `KUMO` token in all corresponding tests. I want to have utils scripts that make life easier. Thus, all KUMO-related scripts need to be updated.

## Expected Outcome
- [x] updated `./utils/deploymentGasAndBytecode.js` with `KUMO` contracts
- [x] updated `./utils/deploymentHelpers.js` with `KUMO`contracts
- [x] updated `./utils/hintExamples.js` with `KUMO` contracts
- [x] updated `./utils/mainnetDeploymentHelpers.js` with `KUSD` contracts
- [x] updated `./utils/proxyHelpers.js` with `KUMO` contracts
- [x] updated `./utils/testHelpers.js` with `KUMO` contracts
- [x] updated `./utils/truffleDeploymentHelpers .js` with `KUMO` contracts

**Comment by wollooo** [comment]
done at [#66](https://github.com/kumodao/borrowprot/pull/66)
