### ISSUE TITLE
Integrate KUMO token in all Smart Contract Tests

### ISSUE THREAD

**Issue by udosson** [kumodao/borrowprot#44]
## Description
As a smart contract developer, I strive for 100% test coverage. Therefore, I need to integrate the `KUMO` token in all corresponding tests and also update the `utils` scripts. In the end, I want to remove `LQTY` from all tests and replace it with `KUMO`.

## Expected Outcome
- [x] #41 
- [x] #45

**Comment by wollooo** [comment]
done at [#66](https://github.com/kumodao/borrowprot/pull/66)
