### ISSUE TITLE
LL: Migrate Price Feeds to Polygon

### ISSUE THREAD

**Issue by udosson** [kumodao/borrowprot#96]
## Overview
As a user of the lending protocol, I want to have an accurate and reliable price feed for the prices of the different types of collateral on the Polygon and the Mumbai network.

## Intended Outcome
Update the Chainlink and Tellor smart contracts and adjust the deployment to work on Polygon and Mumbai.

## Tasks
- [x] #97  
- [x] #98 
- [x] #99 
- [x] #100 
- [x] Update Tellor and Chainlink smart contract addresses and create the config files accordingly (remove the unused once from Liquity)

**Comment by arthurka-o** [comment]
Will be reviewed at https://github.com/kumodao/borrowprot/issues/30
