### ISSUE TITLE
Update Tellor smart contracts

### ISSUE THREAD

**Issue by udosson** [kumodao/borrowprot#97]
## Description
As a user of the lending protocol, I want the system to integrate the most recent version of Tellor smart contracts.

## Context
Tellor changed `requestId` (unit) to `queryId` (bytes32) 6 months ago.

## Expected Outcome
Updated all Tellor Smart Contracts
- [x] Update `./Dependencies/ITellor.sol` according to https://github.com/tellor-io/usingtellor/blob/master/contracts/interface/ITellor.sol
- [x] Update `./Dependencies/TellorCaller.sol` according to https://github.com/tellor-io/usingtellor/blob/master/contracts/UsingTellor.sol#L31

**Comment by arthurka-o** [comment]
Done in https://github.com/kumodao/borrowprot/commit/94c2985aaf6620669c224433ab57b562dba24df2

**Comment by arthurka-o** [comment]
Will be reviewed in https://github.com/kumodao/borrowprot/issues/30
