### ISSUE TITLE
Adjust PriceFeed.sol to updated Tellor Smart Contracts

### ISSUE THREAD

**Issue by udosson** [kumodao/borrowprot#98]
## Description
As a user of the lending protocol, I want the price feed logic to be based on the newest Tellor smart contracts.

## Expected Outcome
Updated the all Tellor related price feed logic
- [x] Update `./Interfaces/ITellorCaller.sol`
- [x] Update `./PriceFeed.sol`
- [x] Adjust price feed related tests if needed

**Comment by arthurka-o** [comment]
Fixed tests here https://github.com/kumodao/borrowprot/commit/7fc87f6b7d29cd0bc152b464cdd06522f058bc7e

**Comment by arthurka-o** [comment]
Will be reviewed at https://github.com/kumodao/borrowprot/issues/30
