### ISSUE TITLE
Update Chainlink Smart Contract

### ISSUE THREAD

**Issue by udosson** [kumodao/borrowprot#99]
## Description
As a user of the lending protocol, I want the system to integrate the most recent version of Chainlink smart contracts.

## Expected Outcome
Updated all Chainlink Smart Contracts
- [x] Update `Dependencies\AggregatorV3Interface.sol`  according to https://github.com/smartcontractkit/chainlink/blob/v1.4.0/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol

**Comment by arthurka-o** [comment]
Our `AggregatorV3Interface` ([link](https://github.com/kumodao/borrowprot/blob/main/packages/contracts/contracts/Dependencies/AggregatorV3Interface.sol)) is the same as on the link ([link](https://github.com/smartcontractkit/chainlink/blob/v1.4.0/contracts/src/v0.8/interfaces/AggregatorV3Interface.sol))

**Comment by udosson** [comment]
Perfect. Then we don't need to update anything. Thanks @arthurka-o
